# Generated by Django 6.0.3 on 2026-03-31 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mera Adı')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('lat', models.FloatField(verbose_name='Enlem')),
                ('lng', models.FloatField(verbose_name='Boylam')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Mera',
                'verbose_name_plural': 'Meralar',
            },
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Balık Adı')),
                ('min_pressure', models.FloatField(blank=True, null=True, verbose_name='Min. Basınç')),
                ('max_pressure', models.FloatField(blank=True, null=True, verbose_name='Max. Basınç')),
                ('min_temp', models.FloatField(blank=True, null=True, verbose_name='Min. Sıcaklık')),
                ('max_temp', models.FloatField(blank=True, null=True, verbose_name='Max. Sıcaklık')),
                ('best_season', models.CharField(blank=True, max_length=50, null=True, verbose_name='En İyi Sezon')),
                ('bait', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yem')),
                ('rod', models.CharField(blank=True, max_length=100, null=True, verbose_name='Olta')),
                ('line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Misina')),
            ],
            options={
                'verbose_name': 'Balık Türü',
                'verbose_name_plural': 'Balık Türleri',
            },
        ),
        migrations.CreateModel(
            name='SpotFishRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abundance', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yoğunluk')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_relations', to='fishing.fishspecies')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_relations', to='fishing.fishingspot')),
            ],
            options={
                'verbose_name': 'Mera-Balık İlişkisi',
                'verbose_name_plural': 'Mera-Balık İlişkileri',
            },
        ),
    ]
