# Generated by Django 6.0.3 on 2026-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingspot',
            name='ai_base_advice',
            field=models.TextField(blank=True, null=True, verbose_name='AI Temel Tavsiyesi'),
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='max_pressure',
            field=models.FloatField(default=1030.0, verbose_name='İdeal Max Basınç (hPa)'),
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='max_temp',
            field=models.FloatField(default=30.0, verbose_name='İdeal Max Sıcaklık (°C)'),
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='min_pressure',
            field=models.FloatField(default=1000.0, verbose_name='İdeal Min Basınç (hPa)'),
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='min_temp',
            field=models.FloatField(default=5.0, verbose_name='İdeal Min Sıcaklık (°C)'),
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle'),
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='spot_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mera Tipi'),
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='water_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Su Tipi'),
        ),
    ]
